config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  get 'orders', to: 'orders#index'
  get '/order_dog_food', to: 'orders#dog_food'
  get '/order_cat_food', to: 'orders#cat_food'
  get '/order_rodent_food', to: 'orders#rodent_food'
  get '/order_all_food', to: 'orders#all_food'
  get '/clear_orders', to: 'orders#clear_orders'

  get '/messages/send_success', to: 'messages#send_success_message'
  get '/messages/send_failure', to: 'messages#send_success_failure'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat_food.rb
class CatFood < ApplicationRecord
end

app/models/dog_food.rb
class DogFood < ApplicationRecord
end

app/models/dog_toy.rb
class DogToy < ApplicationRecord
end

app/models/order_message.rb
class OrderMessage < ApplicationRecord
end

app/models/rodent_food.rb
class RodentFood < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
        @dog_food_orders = DogFood.all
        @cat_food_orders = CatFood.all
        @rodent_food_orders = RodentFood.all

        @order_messages = OrderMessage.all
    end

    def dog_food
        OrderDogFoodJob.perform_async
        redirect_to orders_path, flash: { alert: "Dog Food Ordered" }
    end

    def cat_food
        OrderCatFoodJob.perform_async
        redirect_to orders_path, flash: { alert: "Cat Food Ordered" }
    end

    def rodent_food
        OrderRodentFoodJob.perform_async
        redirect_to orders_path, flash: { alert: "Rodent Food Ordered" }
    end

    def all_food
        OrderAllFoodJob.perform_async
        redirect_to orders_path, flash: { alert: "All Food Ordered" }
    end

    def clear_orders
        DogFood.delete_all
        CatFood.delete_all
        RodentFood.delete_all
        OrderMessage.delete_all

        redirect_to orders_path, flash: { alert: "All Orders Deleted" }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DagRunner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div>
  <h1>Welcome to the Ordering Page!</h1>
    <p id="alert"><%= flash[:alert] %></p>

  <hr />
  <pre>
    <%= link_to "Order Dog Food", order_dog_food_path %>
  </pre>
  <pre>
    <%= link_to "Order Cat Food", order_cat_food_path %>
  </pre>
  <pre>
    <%= link_to "Order Rodent Food", order_rodent_food_path %>
  </pre>
  <pre>
    <%= link_to "Order All Food", order_all_food_path %>
  </pre>
  <pre>
    <%= link_to "Clear All Orders", clear_orders_path %>
  </pre>
  
  <hr />

    Dog Food Orders:
    <% if @dog_food_orders.empty? %>
      No dog food orders!
    <% else %>
      <table class="table">
          <% @dog_food_orders.each do |dog_food_order, index| %>                    
              <tr>
              <td><%= dog_food_order.text %></td>
              </tr>
          <% end %>
      </table>
    <% end %>
    <hr />
    Cat Food Orders:
    <% if @cat_food_orders.empty? %>
      No cat food orders!
    <% else %>
      <table class="table">
          <% @cat_food_orders.each do |cat_food_order, index| %>                    
              <tr>
              <td><%= cat_food_order.text %></td>
              </tr>
          <% end %>
      </table>
    <% end %>
    <hr />
    Rodent Food Orders:
    <% if @dog_food_orders.empty? %>
      No rodent food orders!
    <% else %>
      <table class="table">
          <% @rodent_food_orders.each do |rodent_food_order, index| %>                    
              <tr>
              <td><%= rodent_food_order.text %></td>
              </tr>
          <% end %>
      </table>
    <% end %>
    <hr />
    <br />
    <br />
    <hr />

    Messages sent:
    <table class="table">
        <% @order_messages.each do |order_message, index| %>                    
            <tr>
            <td><%= order_message.text %></td>
            </tr>
        <% end %>
    </table>
</div>